config/routes.rb
Rails.application.routes.draw do
  resources :sample_images

end

app/models/sample_image.rb
class SampleImage < ActiveRecord::Base
  dragonfly_accessor :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sample_images_controller.rb
class SampleImagesController < ApplicationController
  before_action :set_sample_image, only: [:show, :edit, :update, :destroy]

  # GET /sample_images
  # GET /sample_images.json
  def index
    @sample_images = SampleImage.all
  end

  # GET /sample_images/1
  # GET /sample_images/1.json
  def show
  end

  # GET /sample_images/new
  def new
    @sample_image = SampleImage.new
  end

  # GET /sample_images/1/edit
  def edit
  end

  # POST /sample_images
  # POST /sample_images.json
  def create
    @sample_image = SampleImage.new(sample_image_params)

    respond_to do |format|
      if @sample_image.save
        format.html { redirect_to @sample_image, notice: 'Sample image was successfully created.' }
        format.json { render :show, status: :created, location: @sample_image }
      else
        format.html { render :new }
        format.json { render json: @sample_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_images/1
  # PATCH/PUT /sample_images/1.json
  def update
    respond_to do |format|
      if @sample_image.update(sample_image_params)
        format.html { redirect_to @sample_image, notice: 'Sample image was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample_image }
      else
        format.html { render :edit }
        format.json { render json: @sample_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_images/1
  # DELETE /sample_images/1.json
  def destroy
    @sample_image.destroy
    respond_to do |format|
      format.html { redirect_to sample_images_url, notice: 'Sample image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_image
      @sample_image = SampleImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_image_params
      params.require(:sample_image).permit(:name, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sample_images_helper.rb
module SampleImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DfTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sample_images/_form.html.erb
<%= form_for(@sample_image) do |f| %>
  <% if @sample_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample_image.errors.count, "error") %> prohibited this sample_image from being saved:</h2>

      <ul>
      <% @sample_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sample_images/edit.html.erb
<h1>Editing sample_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample_image %> |
<%= link_to 'Back', sample_images_path %>

app/views/sample_images/index.html.erb
<h1>Listing sample_images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_images.each do |sample_image| %>
      <tr>
        <td><%= sample_image.name %></td>
        <td><%= link_to 'Show', sample_image %></td>
        <td><%= link_to 'Edit', edit_sample_image_path(sample_image) %></td>
        <td><%= link_to 'Destroy', sample_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample image', new_sample_image_path %>

app/views/sample_images/new.html.erb
<h1>New sample_image</h1>

<%= render 'form' %>

<%= link_to 'Back', sample_images_path %>

app/views/sample_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sample_image.name %>
</p>

<h1>Original</h1>
<%= image_tag @sample_image.file.url %>
<h2>300x300</h2>
<%= image_tag @sample_image.file.thumb('300x300').url %>
<h2>100x100</h2>
<%= image_tag @sample_image.file.thumb('100x100').url %>
<h2>50x50</h2>
<%= image_tag @sample_image.file.thumb('50x50').url %>

<div>
<%= link_to 'Edit', edit_sample_image_path(@sample_image) %> |
<%= link_to 'Back', sample_images_path %>
</div>